
name: Github Issues to Jira Issues
on:
  issues:
    types: [opened, closed, labeled, unlabeled]
  issue_comment:
    types: [created]
jobs:
  sync:
    name: Sync Items
    runs-on: ubuntu-latest
    steps:
      - name: Sync Github Issues to Jira
        uses: jordansilva/github-action-issue-to-jira@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          jiraHost: ${{ secrets.JIRA_HOST }}
          jiraUsername: ${{ secrets.JIRA_USERNAME }}
          jiraPassword: ${{ secrets.JIRA_PASSWORD }} 
          project:  ${{ secrets.JIRA_PROJECTKEY }} 
